# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

sqlite3: &sqlite3
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

mysql: &mysql
  adapter: mysql
  database: pacecar_test
  username: root
  password: 
  host: localhost
  encoding: utf8

mysql2: &mysql2
  adapter: mysql2
  database: pacecar_test
  username: root
  password: 
  host: localhost
  encoding: utf8

pg: &pg
  adapter: postgresql
  port: 5432
  encoding: utf8
  database: pacecar_test

# This is because of appraisal - find the gem which was loaded, and use that driver
test: 
  <<: *<%= Gem.loaded_specs.keys.select { |key| ['sqlite3', 'mysql', 'mysql2', 'pg'].include? key }.first or raise('Database gem was not loaded') %>

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
